name: Sync unobfuscated-worker
on:
  push:
    paths:
      - 'build/unobfuscated-worker.js'  # 监视文件的变化

jobs:
  download_worker_file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Checkout xrw002/BPB-Worker-Panel repository
      - name: Checkout xrw002/BPB-Worker-Panel repository
        uses: actions/checkout@v2
        with:
          repository: 'xrw002/BPB-Worker-Panel'
          token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Verify the file exists in the cloned repo
      - name: Verify file exists in the cloned repository
        run: |
          ls -l BPB-Worker-Panel/build/unobfuscated-worker.js

      # Step 4: Copy unobfuscated-worker.js to the current repo
      - name: Copy unobfuscated-worker.js to the current repo
        run: |
          cp BPB-Worker-Panel/build/unobfuscated-worker.js ./build/unobfuscated-worker.js
          ls -l ./build/unobfuscated-worker.js  # Verify the file has been copied

      # Step 5: Commit and push the updated file
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build/unobfuscated-worker.js
          git commit -m "Update unobfuscated-worker.js"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
